import test,{beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto,createHash,createHmac} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {demo,quarter,sha256,rankTickets,verifyCampaignRecord} from '../dist/src/features/demo.js';
const values=new Map();
Object.defineProperty(globalThis,'localStorage',{value:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k),clear:()=>values.clear()}});
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const fan={id:'test-fan',name:'Test Fan',role:'member'},other={id:'test-other',name:'Other Fan',role:'member'},admin={id:'test-admin',name:'Test Admin',role:'admin'};
const input={title:'A considered review',subject:'Original work',body:'These original observations discuss the pacing, sound and visual choices.',topic:'movies',rating:4,spoiler:false};
beforeEach(()=>values.clear());
async function post(){await demo.post(fan,input);return (await demo.social(fan)).posts.find(p=>p.authorId===fan.id);}
async function published(){const p=await post();await demo.moderate(admin,p.id,'published',1,'');return p;}

test('Calendar quarters use Vietnam midnight and a 20:00 first-day draw',()=>{assert.equal(quarter(new Date('2026-09-30T16:59:59Z')).id,'2026-Q3');assert.equal(quarter(new Date('2026-09-30T17:00:00Z')).id,'2026-Q4');assert.equal(quarter(new Date('2026-12-31T17:00:00Z')).id,'2027-Q1');assert.equal(quarter(new Date('2026-09-01T00:00:00Z')).drawAt,'2026-10-01T13:00:00.000Z');});
test('Native WebCrypto SHA-256 and HMAC ranking match Node independent implementation',async()=>{assert.equal(await sha256('abc'),createHash('sha256').update('abc').digest('hex'));const seed='12'.repeat(32),snap=await sha256('A\nB\nC'),tickets=['A','B','C'];const expected=tickets.map(ticket=>({ticket,h:createHmac('sha256',Buffer.from(seed,'hex')).update(snap+'|'+ticket).digest('hex')})).sort((a,b)=>a.h.localeCompare(b.h)).map(x=>x.ticket);assert.deepEqual(await rankTickets(seed,snap,tickets),expected);});
test('Guest is gated and pending post is not public',async()=>{await assert.rejects(()=>demo.post(null,input));const p=await post();assert.ok(!(await demo.social(null)).posts.some(x=>x.id===p.id));assert.ok((await demo.social(fan)).posts.some(x=>x.id===p.id));});
for(const patch of [{title:'a'},{body:'x'},{topic:'other'},{rating:6},{rating:1.5},{subject:''}])test('Post validation '+JSON.stringify(patch),async()=>{await assert.rejects(()=>demo.post(fan,{...input,...patch}));});
test('Author cannot self-review; duplicate review is rejected',async()=>{await demo.post(admin,input);const own=(await demo.social(admin)).posts.find(p=>p.authorId===admin.id);await assert.rejects(()=>demo.moderate(admin,own.id,'published',1,''));const p=await published();await assert.rejects(()=>demo.moderate(admin,p.id,'published',1,''));});
test('Edits return to moderation and enforce author/version',async()=>{const p=await published();await assert.rejects(()=>demo.post(other,input,p.id,2));await assert.rejects(()=>demo.post(fan,input,p.id,1));await demo.post(fan,{...input,title:'A changed perspective'},p.id,2);assert.equal((await demo.social(fan)).posts.find(x=>x.id===p.id).status,'pending');});
test('One reaction per user, replacement, unreact and guest block',async()=>{const p=await published();await demo.react(fan,p.id,'like');await demo.react(fan,p.id,'like');await demo.react(fan,p.id,'heart');assert.deepEqual((await demo.social(null)).reactions.filter(x=>x.postId===p.id),[{postId:p.id,userId:fan.id,kind:'heart'}]);await demo.react(fan,p.id,null);assert.equal((await demo.social(null)).reactions.filter(x=>x.postId===p.id).length,0);await assert.rejects(()=>demo.react(null,p.id,'heart'));});
test('Comments enforce reply parent scope/depth and soft deletion',async()=>{const p=await published();await demo.comment(fan,p.id,'First comment');const c=(await demo.social(fan)).comments.find(c=>c.postId===p.id);await demo.comment(other,p.id,'A reply',c.id);const r=(await demo.social(fan)).comments.find(x=>x.parentId===c.id);await assert.rejects(()=>demo.comment(fan,p.id,'Too deep',r.id));await assert.rejects(()=>demo.comment(fan,'post-sound','Wrong post',c.id));await assert.rejects(()=>demo.removeComment(other,c.id));await demo.removeComment(fan,c.id);assert.equal((await demo.social(null)).comments.find(x=>x.id===c.id).body,'Comment removed.');});
test('Reports are private, unique while open, and moderatable',async()=>{await demo.report(fan,'post-city','Personal attack or harassment');await assert.rejects(()=>demo.report(fan,'post-city','Duplicate report'));assert.equal((await demo.social(fan)).reports.length,0);const r=(await demo.social(admin)).reports[0];await demo.resolveReport(admin,r.id,true);assert.ok(!(await demo.social(null)).posts.some(p=>p.id==='post-city'));});
test('Lore Gojo reply discloses a sample and not LLM',async()=>{const r=await demo.chat(fan,'Explain Gojo Limitless',true,'');assert.equal(r.mode,'extractive-demo');assert.equal(r.sources[0].id,'gojo-limitless');assert.equal(r.sources[0].sample,true);});
test('Unknown film is not answered using an unrelated sample',async()=>{const r=await demo.chat(fan,'Summarize the movie Unknown Zebra 999',true,'');assert.equal(r.mode,'no-source');assert.equal(r.sources.length,0);});
test('Lore topic and spoiler filters are applied before selection',async()=>{const r=await demo.chat(fan,'Gojo Limitless',true,'Neon Horizon');assert.equal(r.sources.length,0);const safe=await demo.chat(fan,'Neon Horizon',true,'');assert.ok(safe.sources.every(x=>x.spoilerLevel===0));assert.ok(!safe.text.includes('SPOILER TEST FIXTURE'));});
test('Chat history is scoped and can be cleared',async()=>{await demo.saveChat(fan,[{id:'a',role:'user',text:'Question'}]);assert.equal((await demo.history(fan)).length,1);assert.equal((await demo.history(other)).length,0);await demo.clearChat(fan);assert.equal((await demo.history(fan)).length,0);});
test('Entry is free/explicit/idempotent and admin cannot enter',async()=>{const c=await demo.campaign(fan);await assert.rejects(()=>demo.enter(fan,c.id,false));await assert.rejects(()=>demo.enter(admin,c.id,true));await demo.enter(fan,c.id,true);const first=await demo.campaign(fan);await demo.enter(fan,c.id,true);assert.equal((await demo.campaign(fan)).entryCount,1);assert.equal((await demo.campaign(fan)).myEntry.ticket,first.myEntry.ticket);assert.equal((await demo.campaign(other)).myEntry,null);assert.ok(!('privateSeed' in first));});
test('Empty draw is blocked and lock forbids additional entries',async()=>{const c=await demo.campaign(fan);await assert.rejects(()=>demo.freeze(admin,c.id));await assert.rejects(()=>demo.draw(admin,c.id));await demo.enter(fan,c.id,true);await demo.freeze(admin,c.id);await assert.rejects(()=>demo.enter(other,c.id,true));});
test('Draw saves once, awards unique tickets, verifies all ranks and rejects tampering',async()=>{const c=await demo.campaign(fan);for(const u of [fan,other,{...fan,id:'third'},{...fan,id:'fourth'}])await demo.enter(u,c.id,true);await demo.freeze(admin,c.id);await demo.draw(admin,c.id);const result=await demo.campaign(fan);assert.equal(result.winners.length,3);assert.equal(new Set(result.winners.map(x=>x.ticket)).size,3);assert.equal(await verifyCampaignRecord(result),true);await demo.draw(admin,c.id);assert.deepEqual((await demo.campaign(fan)).winners,result.winners);assert.equal(await verifyCampaignRecord({...result,winners:[]}),false);assert.equal(await verifyCampaignRecord({...result,seedReveal:'ab'.repeat(32)}),false);assert.equal(await verifyCampaignRecord({...result,winners:result.winners.map((w,i)=>i? w:{...w,rank:99})}),false);});
test('One entrant receives one prize, not three',async()=>{const c=await demo.campaign(fan);await demo.enter(fan,c.id,true);await demo.freeze(admin,c.id);await demo.draw(admin,c.id);const r=await demo.campaign(fan);assert.equal(r.winners.length,1);assert.ok(await verifyCampaignRecord(r));});
test('Product source contains no emoji pictographs',()=>{const roots=['src','public/art'];let checked=0;function visit(folder){for(const x of fs.readdirSync(folder,{withFileTypes:true})){const p=path.join(folder,x.name);if(x.isDirectory())visit(p);else if(/\.(tsx?|css|svg)$/.test(p)){assert.equal(/\p{Extended_Pictographic}/u.test(fs.readFileSync(p,'utf8')),false,p);checked++;}}}for(const r of roots)visit(new URL('../'+r,import.meta.url).pathname);assert.ok(checked>20);});
