"""Initial relational schema; generated once from the reviewed SQLAlchemy metadata.

Revision ID: 20260924_01
Revises: None
"""
from alembic import op
import sqlalchemy as sa
revision = "20260924_01"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('fandoms',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fandoms')),
    sa.UniqueConstraint('slug', name=op.f('uq_fandoms_slug'))
    )
    op.create_table('faqs',
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    op.create_table('genres',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('media_assets',
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('attribution', sa.String(length=300), nullable=False),
    sa.Column('license_label', sa.String(length=120), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('image','video','audio','caption')", name=op.f('ck_media_assets_kind')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_media_assets_byte_size')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_assets_owner_id_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_assets_storage_key'))
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('avatar_media_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('member','admin')", name=op.f('ck_users_role')),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media_assets.id'], name=op.f('fk_users_avatar_media_id_media_assets'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_auth_sessions'))
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_threads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_threads'))
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('fan_submissions',
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('fandom_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name=op.f('ck_fan_submissions_status')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_fan_submissions_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_fan_submissions_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fandom_id'], ['fandoms.id'], name=op.f('fk_fan_submissions_fandom_id_fandoms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fan_submissions'))
    )
    op.create_index('ix_submissions_queue', 'fan_submissions', ['status', 'created_at'], unique=False)
    op.create_table('fandom_categories',
    sa.Column('fandom_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_fandom_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fandom_id'], ['fandoms.id'], name=op.f('fk_fandom_categories_fandom_id_fandoms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fandom_id', 'category_id', name=op.f('pk_fandom_categories'))
    )
    op.create_table('feedback',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('bug','suggestion','query')", name=op.f('ck_feedback_kind')),
    sa.CheckConstraint("status IN ('open','in_progress','resolved')", name=op.f('ck_feedback_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('one_time_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("purpose IN ('verify_email','reset_password')", name=op.f('ck_one_time_tokens_purpose')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_one_time_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_one_time_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_one_time_tokens_token_hash'))
    )
    op.create_index(op.f('ix_one_time_tokens_user_id'), 'one_time_tokens', ['user_id'], unique=False)
    op.create_table('user_categories',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_user_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_user_categories'))
    )
    op.create_table('user_fandoms',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fandom_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['fandom_id'], ['fandoms.id'], name=op.f('fk_user_fandoms_fandom_id_fandoms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_fandoms_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'fandom_id', name=op.f('pk_user_fandoms'))
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.String(length=8), nullable=False),
    sa.Column('font_scale', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('spoiler_safe', sa.Boolean(), nullable=False),
    sa.CheckConstraint("theme IN ('light','dark','system')", name=op.f('ck_user_settings_theme')),
    sa.CheckConstraint('font_scale IN (100,112.5,125)', name=op.f('ck_user_settings_font_scale')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('client_message_id', sa.String(length=36), nullable=True),
    sa.Column('model_label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_messages_thread_id_chat_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages')),
    sa.UniqueConstraint('thread_id', 'client_message_id', name=op.f('uq_chat_messages_thread_id'))
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_moderation_actions_reviewer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['fan_submissions.id'], name=op.f('fk_moderation_actions_submission_id_fan_submissions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_actions'))
    )
    op.create_index(op.f('ix_moderation_actions_submission_id'), 'moderation_actions', ['submission_id'], unique=False)
    op.create_table('resources',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('fandom_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('cover_media_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('has_spoilers', sa.Boolean(), nullable=False),
    sa.Column('spoiler_level', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('article','character','video','audio','gallery','merchandise','event')", name=op.f('ck_resources_kind')),
    sa.CheckConstraint("status IN ('draft','published','archived')", name=op.f('ck_resources_status')),
    sa.CheckConstraint('release_year IS NULL OR (release_year >= 1900 AND release_year <= 2100)', name=op.f('ck_resources_release_year')),
    sa.CheckConstraint('version > 0', name=op.f('ck_resources_version')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_resources_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_resources_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_assets.id'], name=op.f('fk_resources_cover_media_id_media_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fandom_id', 'category_id'], ['fandom_categories.fandom_id', 'fandom_categories.category_id'], name=op.f('fk_resources_fandom_id_fandom_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['fan_submissions.id'], name=op.f('fk_resources_submission_id_fan_submissions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('slug', name=op.f('uq_resources_slug')),
    sa.UniqueConstraint('submission_id', name=op.f('uq_resources_submission_id'))
    )
    op.create_index('ix_resources_category_kind', 'resources', ['category_id', 'kind', 'status'], unique=False)
    op.create_index('ix_resources_public_feed', 'resources', ['status', 'published_at', 'id'], unique=False)
    op.create_table('activities',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_activities_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('user_id', 'resource_id', 'day', name=op.f('uq_activities_user_id'))
    )
    op.create_table('bookmarks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_bookmarks_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks')),
    sa.UniqueConstraint('user_id', 'resource_id', name=op.f('uq_bookmarks_user_id'))
    )
    op.create_index('ix_bookmarks_user_created', 'bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_table('character_profiles',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('continuity', sa.String(length=120), nullable=False),
    sa.Column('biography_markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_character_profiles_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_character_profiles'))
    )
    op.create_table('event_details',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('ticket_url', sa.String(length=1000), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_event_details_time_range')),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_event_details_latitude')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_event_details_longitude')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_event_details_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_event_details'))
    )
    op.create_index('ix_event_city_start', 'event_details', ['city', 'starts_at'], unique=False)
    op.create_table('merchandise_items',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('maker', sa.String(length=120), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=False),
    sa.Column('official_url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_merchandise_items_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_merchandise_items'))
    )
    op.create_table('message_sources',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_message_sources_message_id_chat_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_message_sources_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'resource_id', name=op.f('pk_message_sources'))
    )
    op.create_table('ratings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('value >= 1 AND value <= 5', name=op.f('ck_ratings_value')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_ratings_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', name=op.f('pk_ratings'))
    )
    op.create_table('resource_genres',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_resource_genres_genre_id_genres'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_genres_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'genre_id', name=op.f('pk_resource_genres'))
    )
    op.create_table('resource_media',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_resource_media_media_id_media_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_media_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'media_id', name=op.f('pk_resource_media'))
    )
    op.create_table('resource_tags',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_tags_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_resource_tags_tag_id_tags'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('resource_id', 'tag_id', name=op.f('pk_resource_tags'))
    )
    op.create_table('upcoming_releases',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('date_precision', sa.String(length=12), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_upcoming_releases_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upcoming_releases'))
    )
    op.create_index('ix_release_date', 'upcoming_releases', ['release_date', 'resource_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key('fk_media_assets_owner_id_users', 'media_assets', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
        op.create_foreign_key('fk_users_avatar_media_id_media_assets', 'users', 'media_assets', ['avatar_media_id'], ['id'], ondelete='SET NULL')


def downgrade():
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint('fk_media_assets_owner_id_users', 'media_assets', type_="foreignkey")
        op.drop_constraint('fk_users_avatar_media_id_media_assets', 'users', type_="foreignkey")
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_release_date', table_name='upcoming_releases')
    op.drop_table('upcoming_releases')
    op.drop_table('resource_tags')
    op.drop_table('resource_media')
    op.drop_table('resource_genres')
    op.drop_table('ratings')
    op.drop_table('message_sources')
    op.drop_table('merchandise_items')
    op.drop_index('ix_event_city_start', table_name='event_details')
    op.drop_table('event_details')
    op.drop_table('character_profiles')
    op.drop_index('ix_bookmarks_user_created', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_table('activities')
    op.drop_index('ix_resources_public_feed', table_name='resources')
    op.drop_index('ix_resources_category_kind', table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_moderation_actions_submission_id'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('user_settings')
    op.drop_table('user_fandoms')
    op.drop_table('user_categories')
    op.drop_index(op.f('ix_one_time_tokens_user_id'), table_name='one_time_tokens')
    op.drop_table('one_time_tokens')
    op.drop_table('feedback')
    op.drop_table('fandom_categories')
    op.drop_index('ix_submissions_queue', table_name='fan_submissions')
    op.drop_table('fan_submissions')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('media_assets')
    op.drop_table('genres')
    op.drop_table('faqs')
    op.drop_table('fandoms')
    op.drop_table('categories')
    # ### end Alembic commands ###
